[install]
optional = true
peer = true
production = false
exact = false
saveTextLockfile = false
auto = "fallback"
linker = "hoisted"

[debug]
editor = "code"

[run]
shell = "bun"
bun = true

[test]
root = "./"
coverage = true
coverageThreshold = 0.9
coverageSkipTestFiles = false
randomize = true
